{"timestamp": "2025-05-19T21:45:30.382156-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:45:30", "taskName": null}
{"timestamp": "2025-05-19T21:45:33.921246-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:45:33", "taskName": null}
{"timestamp": "2025-05-19T21:46:25.190471-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:46:25", "taskName": null}
{"timestamp": "2025-05-19T21:51:17.440175-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:51:17", "taskName": null}
{"timestamp": "2025-05-19T21:59:22.471122-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:59:22", "taskName": null}
{"timestamp": "2025-05-19T21:59:25.592538-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "21:59:25", "taskName": null}
{"timestamp": "2025-05-19T22:05:03.493231-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "22:05:03", "taskName": null}
{"timestamp": "2025-05-19T22:05:07.372517-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "22:05:07", "taskName": null}
{"timestamp": "2025-05-19T22:17:25.183918-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "22:17:25", "taskName": null}
{"timestamp": "2025-05-19T22:40:57.574699-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-19", "time": "22:40:57", "taskName": null}
{"timestamp": "2025-05-20T06:28:42.778880-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:28:42", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:30:58.660911-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:30:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:34:57.789266-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:34:57", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:37:13.662471-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:37:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:41:12.792479-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:41:12", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:43:28.670357-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:43:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:47:27.802921-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:47:27", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:48:43.749106-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:48:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:53:42.815980-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:53:42", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:54:58.757950-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:54:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T06:59:57.913926-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "06:59:57", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:00:13.814841-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:00:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:06:12.918627-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:06:12", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:06:28.821224-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:06:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:12:27.949004-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:12:27", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:12:43.835635-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:12:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:18:42.944302-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:18:42", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:18:58.828899-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:18:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:24:57.948381-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:24:57", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:25:13.833409-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:25:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:31:12.955959-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:31:12", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:31:28.834072-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:31:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:37:27.952696-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:37:27", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:37:43.941225-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:37:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:43:42.954155-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:43:42", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:43:58.951457-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:43:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:49:57.954945-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:49:57", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:50:13.952773-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:50:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:56:12.969051-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:56:12", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T07:56:28.955294-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "07:56:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:01:43.982700-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:01:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:02:27.982807-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:02:27", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:07:58.983024-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:07:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:08:42.986583-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:08:42", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:14:13.996550-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:14:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:14:57.984796-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:14:57", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:19:29.075432-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:19:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:21:12.991267-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:21:12", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:25:44.070682-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:25:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:26:28.098072-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:26:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:31:59.072807-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:31:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:32:43.106531-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:32:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:38:14.072686-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:38:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:38:58.105911-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:38:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:44:29.070183-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:44:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:45:13.168362-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:45:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:50:44.077417-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:50:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:51:28.178244-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:51:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:56:59.088405-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:56:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T08:57:43.183706-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "08:57:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:03:14.088567-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:03:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:03:58.197703-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:03:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:09:13.225314-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:09:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:09:29.092431-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:09:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:14:44.168715-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:14:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:15:28.226517-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:15:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:19:59.232777-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:19:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:20:43.272622-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:20:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:26:14.333761-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:26:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:26:58.274756-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:26:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:32:29.333495-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:32:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:33:13.275184-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:33:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:38:44.343092-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:38:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:39:28.300371-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:39:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:44:59.353618-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:44:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:45:43.300509-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:45:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:51:14.347115-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:51:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:51:58.304498-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:51:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:57:29.344017-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:57:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T09:58:13.317661-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "09:58:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:02:44.393135-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:02:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:04:28.321505-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:04:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:08:59.401804-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:08:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:10:43.322671-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:10:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:15:14.470820-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:15:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:16:58.323059-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:16:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:21:29.483331-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:21:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:22:13.489474-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:22:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:26:44.565997-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:26:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:27:28.629694-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:27:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:32:59.572471-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:32:59", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:33:43.632793-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:33:43", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:38:58.797616-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:38:58", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:39:14.582033-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:39:14", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:45:13.800453-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:45:13", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:45:29.584992-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:45:29", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:51:28.803322-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:51:28", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:51:44.592392-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "10:51:44", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-20T10:59:42.760966-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-20", "time": "10:59:42", "taskName": null}
{"timestamp": "2025-05-20T10:59:48.277766-03:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-20", "time": "10:59:48", "taskName": null}
{"timestamp": "2025-05-20T16:00:02.853134-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para coletar dados de uso", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-20", "time": "16:00:02", "taskName": null, "task": "collect_data"}
{"timestamp": "2025-05-22T23:46:54.830232-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para coletar dados de uso", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-22", "time": "23:46:54", "taskName": null, "task": "collect_data"}
{"timestamp": "2025-05-23T00:41:10.750875-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para coletar dados de uso", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-23", "time": "00:41:10", "taskName": null, "task": "collect_data"}
{"timestamp": "2025-05-24T13:49:25.660240-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "13:49:25", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-24T13:50:31.593952-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "13:50:31", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-24T13:55:40.662953-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "13:55:40", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-24T13:56:46.703253-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "13:56:46", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-24T14:01:55.667120-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "14:01:55", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-24T14:03:01.779098-03:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-24", "time": "14:03:01", "taskName": null, "task": "check_limits"}
{"timestamp": "2025-05-31T13:02:59.381130+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:02:59"}
{"timestamp": "2025-05-31T13:03:01.405209+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:01"}
{"timestamp": "2025-05-31T13:03:04.337829+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:04"}
{"timestamp": "2025-05-31T13:03:08.074252+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:08"}
{"timestamp": "2025-05-31T13:03:12.252267+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:12"}
{"timestamp": "2025-05-31T13:03:18.661028+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:18"}
{"timestamp": "2025-05-31T13:03:23.786132+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:23"}
{"timestamp": "2025-05-31T13:03:32.239881+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:32"}
{"timestamp": "2025-05-31T13:03:47.060476+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:03:47"}
{"timestamp": "2025-05-31T13:04:14.904599+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:04:14"}
{"timestamp": "2025-05-31T13:24:28.366603+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:28"}
{"timestamp": "2025-05-31T13:24:32.176351+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:32"}
{"timestamp": "2025-05-31T13:24:35.123224+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:35"}
{"timestamp": "2025-05-31T13:24:38.772453+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:38"}
{"timestamp": "2025-05-31T13:24:43.096080+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:43"}
{"timestamp": "2025-05-31T13:24:48.995152+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:48"}
{"timestamp": "2025-05-31T13:24:54.360830+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:24:54"}
{"timestamp": "2025-05-31T13:25:02.654813+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:25:02"}
{"timestamp": "2025-05-31T13:25:17.507867+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:25:17"}
{"timestamp": "2025-05-31T13:25:45.312517+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:25:45"}
{"timestamp": "2025-05-31T13:26:38.492113+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:26:38"}
{"timestamp": "2025-05-31T13:27:40.621636+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:27:40"}
{"timestamp": "2025-05-31T13:28:42.492525+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:28:42"}
{"timestamp": "2025-05-31T13:29:44.423805+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:29:44"}
{"timestamp": "2025-05-31T13:30:46.579054+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:30:46"}
{"timestamp": "2025-05-31T13:31:48.564213+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:31:48"}
{"timestamp": "2025-05-31T13:32:50.526215+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:32:50"}
{"timestamp": "2025-05-31T13:33:52.552775+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:33:52"}
{"timestamp": "2025-05-31T13:34:55.080453+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:34:55"}
{"timestamp": "2025-05-31T13:35:57.045100+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:35:57"}
{"timestamp": "2025-05-31T13:36:59.032261+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:36:59"}
{"timestamp": "2025-05-31T13:38:01.149640+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:38:01"}
{"timestamp": "2025-05-31T13:39:03.097343+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:39:03"}
{"timestamp": "2025-05-31T13:40:05.243041+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:40:05"}
{"timestamp": "2025-05-31T13:41:07.120769+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:41:07"}
{"timestamp": "2025-05-31T13:42:09.242719+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:42:09"}
{"timestamp": "2025-05-31T13:43:11.138135+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:43:11"}
{"timestamp": "2025-05-31T13:44:13.122705+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:44:13"}
{"timestamp": "2025-05-31T13:45:15.222186+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:45:15"}
{"timestamp": "2025-05-31T13:46:17.100097+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:46:17"}
{"timestamp": "2025-05-31T13:52:21.500010+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "13:52:21"}
{"timestamp": "2025-05-31T13:57:31.705203+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "13:57:31", "task": "check_limits"}
{"timestamp": "2025-05-31T14:02:41.718913+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:02:41", "task": "check_limits"}
{"timestamp": "2025-05-31T14:04:53.903613+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "14:04:53"}
{"timestamp": "2025-05-31T14:10:03.984806+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:10:03", "task": "check_limits"}
{"timestamp": "2025-05-31T14:22:47.475720+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "14:22:47"}
{"timestamp": "2025-05-31T14:27:57.543826+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:27:57", "task": "check_limits"}
{"timestamp": "2025-05-31T14:33:07.554047+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:33:07", "task": "check_limits"}
{"timestamp": "2025-05-31T14:38:17.566314+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:38:17", "task": "check_limits"}
{"timestamp": "2025-05-31T14:43:27.571512+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:43:27", "task": "check_limits"}
{"timestamp": "2025-05-31T14:48:37.583652+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "14:48:37", "task": "check_limits"}
{"timestamp": "2025-05-31T14:55:54.726590+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "14:55:54"}
{"timestamp": "2025-05-31T15:01:05.207170+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:01:05", "task": "check_limits"}
{"timestamp": "2025-05-31T15:06:15.220156+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:06:15", "task": "check_limits"}
{"timestamp": "2025-05-31T15:11:25.230348+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:11:25", "task": "check_limits"}
{"timestamp": "2025-05-31T15:16:35.242695+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:16:35", "task": "check_limits"}
{"timestamp": "2025-05-31T15:21:45.252594+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:21:45", "task": "check_limits"}
{"timestamp": "2025-05-31T15:26:55.265687+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:26:55", "task": "check_limits"}
{"timestamp": "2025-05-31T15:32:05.275839+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:32:05", "task": "check_limits"}
{"timestamp": "2025-05-31T15:37:15.285299+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:37:15", "task": "check_limits"}
{"timestamp": "2025-05-31T15:42:25.294823+00:00", "level": "ERROR", "message": "N\u00e3o foi poss\u00edvel conectar ao MikroTik para verificar limites", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:42:25", "task": "check_limits"}
{"timestamp": "2025-05-31T15:48:27.090454+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "15:48:27"}
{"timestamp": "2025-05-31T15:53:27.707198+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:53:27", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T15:53:27.807479+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:53:27", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T15:58:28.024081+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:58:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T15:58:28.109332+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "15:58:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:03:28.348935+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:03:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:03:28.425483+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:03:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:08:28.669819+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:08:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:08:28.761774+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:08:28", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:13:29.008983+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:13:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:13:29.116893+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:13:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:18:29.345589+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:18:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:18:29.434468+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:18:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:23:29.712795+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:23:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:23:29.785238+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:23:29", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:28:30.073153+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:28:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:28:30.160301+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:28:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:33:30.402299+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:33:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:33:30.483641+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:33:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:38:30.730124+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:38:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:38:30.826165+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:38:30", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:43:31.075637+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:43:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:43:31.167052+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:43:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:48:31.400542+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:48:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:48:31.485498+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:48:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:53:31.741455+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:53:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:53:31.826716+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:53:31", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T16:58:32.095958+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:58:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T16:58:32.188328+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "16:58:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:03:32.473137+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:03:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:03:32.570847+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:03:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:08:32.842946+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:08:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:08:32.936077+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:08:32", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:13:33.184648+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:13:33", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:13:33.278700+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:13:33", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:18:33.518668+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:18:33", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:18:33.600505+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:18:33", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:26:58.446969+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "17:26:58"}
{"timestamp": "2025-05-31T17:29:15.692118+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "17:29:15"}
{"timestamp": "2025-05-31T17:34:16.063502+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:34:16", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:34:16.164239+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:34:16", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:44:34.564002+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "17:44:34"}
{"timestamp": "2025-05-31T17:49:34.932786+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:49:34", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:49:35.027994+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:49:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:54:35.266474+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:54:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:54:35.362251+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:54:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T17:59:35.610800+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:59:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T17:59:35.687155+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "17:59:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:04:35.933985+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:04:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:04:36.027944+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:04:36", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:09:36.294053+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:09:36", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:09:36.390626+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:09:36", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:14:36.670074+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:14:36", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:14:36.761247+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:14:36", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:19:37.032822+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:19:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:19:37.217366+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:19:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:24:37.509032+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:24:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:24:37.609651+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:24:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:29:37.843444+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:29:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:29:37.925223+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:29:37", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:34:38.192856+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:34:38", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:34:38.289520+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:34:38", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:39:38.560944+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:39:38", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:39:38.663085+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:39:38", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:48:19.247186+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "18:48:19"}
{"timestamp": "2025-05-31T18:53:19.519666+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:53:19", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:53:19.611101+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:53:19", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T18:58:19.870206+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:58:19", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T18:58:19.963024+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "18:58:19", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:03:20.228861+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:03:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:03:20.318919+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:03:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:08:20.564856+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:08:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:08:20.643756+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:08:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:13:20.880310+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:13:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:13:20.961070+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:13:20", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:18:21.211283+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:18:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:18:21.302266+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:18:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:23:21.532934+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:23:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:23:21.620595+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:23:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:28:21.877688+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:28:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:28:21.974326+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:28:21", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:33:22.226570+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:33:22", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:33:22.321699+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:33:22", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:38:22.583666+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:38:22", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:38:22.660363+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:38:22", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:43:22.930654+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:43:22", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:43:23.022294+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:43:23", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:47:05.599539+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "19:47:05"}
{"timestamp": "2025-05-31T19:49:54.948262+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "19:49:54"}
{"timestamp": "2025-05-31T19:54:55.233532+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:54:55", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T19:54:55.308356+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "19:54:55", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T19:56:55.206784+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "19:56:55"}
{"timestamp": "2025-05-31T20:02:36.452607+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "20:02:36"}
{"timestamp": "2025-05-31T21:05:01.508583+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "21:05:01"}
{"timestamp": "2025-05-31T21:10:01.839510+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "21:10:01", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T21:10:01.929671+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "21:10:01", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
{"timestamp": "2025-05-31T21:14:35.460806+00:00", "level": "ERROR", "message": "Logger inicializado - error", "module": "logger", "function": "setup_logger", "line": 114, "date": "2025-05-31", "time": "21:14:35"}
{"timestamp": "2025-05-31T21:19:35.751544+00:00", "level": "ERROR", "message": "Erro ao coletar dados de uso: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "21:19:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "collect_data"}
{"timestamp": "2025-05-31T21:19:35.853018+00:00", "level": "ERROR", "message": "Erro ao verificar limites: Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "module": "logger", "function": "log_with_context", "line": 134, "date": "2025-05-31", "time": "21:19:35", "error": "Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.", "task": "check_limits"}
